package com.dyx.mgdp.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dyx.mgdp.greendao.Blog;

import com.dyx.mgdp.greendao.BlogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig blogDaoConfig;

    private final BlogDao blogDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        blogDaoConfig = daoConfigMap.get(BlogDao.class).clone();
        blogDaoConfig.initIdentityScope(type);

        blogDao = new BlogDao(blogDaoConfig, this);

        registerDao(Blog.class, blogDao);
    }
    
    public void clear() {
        blogDaoConfig.getIdentityScope().clear();
    }

    public BlogDao getBlogDao() {
        return blogDao;
    }

}
